### ISSUE TITLE
Any Help?

### ISSUE THREAD

**Issue by circutrider21** [29jm/SnowflakeOS#8]
I was wondering if you needed help with implementing anything or testing

**Comment by 29jm** [comment]
Hey man! I'd love help if you feel like it! There's a ton to do in userspace, much of it quite accessible with the tools available now I think, and of course lots to do on the kernel side, depends if you have a preference, userspace is probably an easier start for a first contribution.

I'll try to make a short list of what comes to mind, but really if you spot something that you think should be improved/fixed you're more than welcome to have a go at it! I'll be happy to help you get started in any case :)

+ a graphical launcher for apps
+ there's this bug in the terminal, where it crashes if a command is launched when the prompt had already reached the bottom of the window, it doesn't seem to happen everytime
+ expanding the ui library: have a textfield widget, a label widget too probably, usability things like a background color property for stuff, a 'close' button in the titlebar
    - rewriting the terminal with the ui library?
+ improving (really, writing) the file viewer `files.c`, allowing some operations on files, folder creation... probably requires some new ui components
+ there's a calculator app proof of concept I used to test the ui lib's vbox and hboxes, but it's a dummy, because it turns out I'm bad at writing parsers; I'd like to see it working some day
+ really any new userspace app, bonus points if it uses a kernel feature not yet showcased by another app ^^
+ porting a rock solid sprintf implementation, like the one from `stb_printf.h`, that'd great

Kernel side stuff:
+ a mouse cursor that's not just nine grey pixels arranged in a square!
+ allow resizing windows in the wm: would probably crash due to memory fragmentation right now, but it could technically be done
+ that's all I think of right now, I'm in the middle of writing my version of a virtual filesystem so it's sort of taking all of my thinking space there

I should probably put this in different github issues or something, this got longer than expected. Anyway, happy to have your interest!

**Comment by circutrider21** [comment]
Ok, I will be happy to get started!

**Comment by the-grue** [comment]
@29jm since you took the time to write up a wish list, maybe copy it over into the wiki?

**Comment by 29jm** [comment]
@the-grue Good call, I'll do something like that !
